// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: CalculatorMsg.proto

package com.zxf.rpc.proto;

public final class CalculatorMsg {
	private CalculatorMsg() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface CalRequestOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required string methodName = 1;
		/**
		 * <code>required string methodName = 1;</code>
		 */
		boolean hasMethodName();

		/**
		 * <code>required string methodName = 1;</code>
		 */
		java.lang.String getMethodName();

		/**
		 * <code>required string methodName = 1;</code>
		 */
		com.google.protobuf.ByteString getMethodNameBytes();

		// required int32 num1 = 2;
		/**
		 * <code>required int32 num1 = 2;</code>
		 */
		boolean hasNum1();

		/**
		 * <code>required int32 num1 = 2;</code>
		 */
		int getNum1();

		// required int32 num2 = 3;
		/**
		 * <code>required int32 num2 = 3;</code>
		 */
		boolean hasNum2();

		/**
		 * <code>required int32 num2 = 3;</code>
		 */
		int getNum2();
	}

	/**
	 * Protobuf type {@code CalRequest}
	 */
	public static final class CalRequest extends
			com.google.protobuf.GeneratedMessage implements CalRequestOrBuilder {
		// Use CalRequest.newBuilder() to construct.
		private CalRequest(
				com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CalRequest(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final CalRequest defaultInstance;

		public static CalRequest getDefaultInstance() {
			return defaultInstance;
		}

		public CalRequest getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CalRequest(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						methodName_ = input.readBytes();
						break;
					}
					case 16: {
						bitField0_ |= 0x00000002;
						num1_ = input.readInt32();
						break;
					}
					case 24: {
						bitField0_ |= 0x00000004;
						num2_ = input.readInt32();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalRequest_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalRequest_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.zxf.rpc.proto.CalculatorMsg.CalRequest.class,
							com.zxf.rpc.proto.CalculatorMsg.CalRequest.Builder.class);
		}

		public static com.google.protobuf.Parser<CalRequest> PARSER = new com.google.protobuf.AbstractParser<CalRequest>() {
			public CalRequest parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CalRequest(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CalRequest> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required string methodName = 1;
		public static final int METHODNAME_FIELD_NUMBER = 1;
		private java.lang.Object methodName_;

		/**
		 * <code>required string methodName = 1;</code>
		 */
		public boolean hasMethodName() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required string methodName = 1;</code>
		 */
		public java.lang.String getMethodName() {
			java.lang.Object ref = methodName_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String) ref;
			} else {
				com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
				java.lang.String s = bs.toStringUtf8();
				if (bs.isValidUtf8()) {
					methodName_ = s;
				}
				return s;
			}
		}

		/**
		 * <code>required string methodName = 1;</code>
		 */
		public com.google.protobuf.ByteString getMethodNameBytes() {
			java.lang.Object ref = methodName_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b = com.google.protobuf.ByteString
						.copyFromUtf8((java.lang.String) ref);
				methodName_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// required int32 num1 = 2;
		public static final int NUM1_FIELD_NUMBER = 2;
		private int num1_;

		/**
		 * <code>required int32 num1 = 2;</code>
		 */
		public boolean hasNum1() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		/**
		 * <code>required int32 num1 = 2;</code>
		 */
		public int getNum1() {
			return num1_;
		}

		// required int32 num2 = 3;
		public static final int NUM2_FIELD_NUMBER = 3;
		private int num2_;

		/**
		 * <code>required int32 num2 = 3;</code>
		 */
		public boolean hasNum2() {
			return ((bitField0_ & 0x00000004) == 0x00000004);
		}

		/**
		 * <code>required int32 num2 = 3;</code>
		 */
		public int getNum2() {
			return num2_;
		}

		private void initFields() {
			methodName_ = "";
			num1_ = 0;
			num2_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasMethodName()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNum1()) {
				memoizedIsInitialized = 0;
				return false;
			}
			if (!hasNum2()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getMethodNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeInt32(2, num1_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				output.writeInt32(3, num2_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeBytesSize(
						1, getMethodNameBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						2, num1_);
			}
			if (((bitField0_ & 0x00000004) == 0x00000004)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						3, num2_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.zxf.rpc.proto.CalculatorMsg.CalRequest)) {
				return super.equals(obj);
			}
			com.zxf.rpc.proto.CalculatorMsg.CalRequest other = (com.zxf.rpc.proto.CalculatorMsg.CalRequest) obj;

			boolean result = true;
			result = result && (hasMethodName() == other.hasMethodName());
			if (hasMethodName()) {
				result = result
						&& getMethodName().equals(other.getMethodName());
			}
			result = result && (hasNum1() == other.hasNum1());
			if (hasNum1()) {
				result = result && (getNum1() == other.getNum1());
			}
			result = result && (hasNum2() == other.hasNum2());
			if (hasNum2()) {
				result = result && (getNum2() == other.getNum2());
			}
			result = result
					&& getUnknownFields().equals(other.getUnknownFields());
			return result;
		}

		private int memoizedHashCode = 0;

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			if (hasMethodName()) {
				hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
				hash = (53 * hash) + getMethodName().hashCode();
			}
			if (hasNum1()) {
				hash = (37 * hash) + NUM1_FIELD_NUMBER;
				hash = (53 * hash) + getNum1();
			}
			if (hasNum2()) {
				hash = (37 * hash) + NUM2_FIELD_NUMBER;
				hash = (53 * hash) + getNum2();
			}
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalRequest parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				com.zxf.rpc.proto.CalculatorMsg.CalRequest prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code CalRequest}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.zxf.rpc.proto.CalculatorMsg.CalRequestOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalRequest_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalRequest_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.zxf.rpc.proto.CalculatorMsg.CalRequest.class,
								com.zxf.rpc.proto.CalculatorMsg.CalRequest.Builder.class);
			}

			// Construct using
			// com.newegg.ec.rpc.proto.CalculatorMsg.CalRequest.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				methodName_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				num1_ = 0;
				bitField0_ = (bitField0_ & ~0x00000002);
				num2_ = 0;
				bitField0_ = (bitField0_ & ~0x00000004);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalRequest_descriptor;
			}

			public com.zxf.rpc.proto.CalculatorMsg.CalRequest getDefaultInstanceForType() {
				return com.zxf.rpc.proto.CalculatorMsg.CalRequest
						.getDefaultInstance();
			}

			public com.zxf.rpc.proto.CalculatorMsg.CalRequest build() {
				com.zxf.rpc.proto.CalculatorMsg.CalRequest result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.zxf.rpc.proto.CalculatorMsg.CalRequest buildPartial() {
				com.zxf.rpc.proto.CalculatorMsg.CalRequest result = new com.zxf.rpc.proto.CalculatorMsg.CalRequest(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.methodName_ = methodName_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.num1_ = num1_;
				if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
					to_bitField0_ |= 0x00000004;
				}
				result.num2_ = num2_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.zxf.rpc.proto.CalculatorMsg.CalRequest) {
					return mergeFrom((com.zxf.rpc.proto.CalculatorMsg.CalRequest) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					com.zxf.rpc.proto.CalculatorMsg.CalRequest other) {
				if (other == com.zxf.rpc.proto.CalculatorMsg.CalRequest
						.getDefaultInstance())
					return this;
				if (other.hasMethodName()) {
					bitField0_ |= 0x00000001;
					methodName_ = other.methodName_;
					onChanged();
				}
				if (other.hasNum1()) {
					setNum1(other.getNum1());
				}
				if (other.hasNum2()) {
					setNum2(other.getNum2());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasMethodName()) {

					return false;
				}
				if (!hasNum1()) {

					return false;
				}
				if (!hasNum2()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.zxf.rpc.proto.CalculatorMsg.CalRequest parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.zxf.rpc.proto.CalculatorMsg.CalRequest) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required string methodName = 1;
			private java.lang.Object methodName_ = "";

			/**
			 * <code>required string methodName = 1;</code>
			 */
			public boolean hasMethodName() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required string methodName = 1;</code>
			 */
			public java.lang.String getMethodName() {
				java.lang.Object ref = methodName_;
				if (!(ref instanceof java.lang.String)) {
					java.lang.String s = ((com.google.protobuf.ByteString) ref)
							.toStringUtf8();
					methodName_ = s;
					return s;
				} else {
					return (java.lang.String) ref;
				}
			}

			/**
			 * <code>required string methodName = 1;</code>
			 */
			public com.google.protobuf.ByteString getMethodNameBytes() {
				java.lang.Object ref = methodName_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b = com.google.protobuf.ByteString
							.copyFromUtf8((java.lang.String) ref);
					methodName_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString) ref;
				}
			}

			/**
			 * <code>required string methodName = 1;</code>
			 */
			public Builder setMethodName(java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				methodName_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required string methodName = 1;</code>
			 */
			public Builder clearMethodName() {
				bitField0_ = (bitField0_ & ~0x00000001);
				methodName_ = getDefaultInstance().getMethodName();
				onChanged();
				return this;
			}

			/**
			 * <code>required string methodName = 1;</code>
			 */
			public Builder setMethodNameBytes(
					com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				methodName_ = value;
				onChanged();
				return this;
			}

			// required int32 num1 = 2;
			private int num1_;

			/**
			 * <code>required int32 num1 = 2;</code>
			 */
			public boolean hasNum1() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			/**
			 * <code>required int32 num1 = 2;</code>
			 */
			public int getNum1() {
				return num1_;
			}

			/**
			 * <code>required int32 num1 = 2;</code>
			 */
			public Builder setNum1(int value) {
				bitField0_ |= 0x00000002;
				num1_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 num1 = 2;</code>
			 */
			public Builder clearNum1() {
				bitField0_ = (bitField0_ & ~0x00000002);
				num1_ = 0;
				onChanged();
				return this;
			}

			// required int32 num2 = 3;
			private int num2_;

			/**
			 * <code>required int32 num2 = 3;</code>
			 */
			public boolean hasNum2() {
				return ((bitField0_ & 0x00000004) == 0x00000004);
			}

			/**
			 * <code>required int32 num2 = 3;</code>
			 */
			public int getNum2() {
				return num2_;
			}

			/**
			 * <code>required int32 num2 = 3;</code>
			 */
			public Builder setNum2(int value) {
				bitField0_ |= 0x00000004;
				num2_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 num2 = 3;</code>
			 */
			public Builder clearNum2() {
				bitField0_ = (bitField0_ & ~0x00000004);
				num2_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:CalRequest)
		}

		static {
			defaultInstance = new CalRequest(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:CalRequest)
	}

	public interface CalResponseOrBuilder extends
			com.google.protobuf.MessageOrBuilder {

		// required int32 result = 1;
		/**
		 * <code>required int32 result = 1;</code>
		 */
		boolean hasResult();

		/**
		 * <code>required int32 result = 1;</code>
		 */
		int getResult();
	}

	/**
	 * Protobuf type {@code CalResponse}
	 */
	public static final class CalResponse extends
			com.google.protobuf.GeneratedMessage implements
			CalResponseOrBuilder {
		// Use CalResponse.newBuilder() to construct.
		private CalResponse(
				com.google.protobuf.GeneratedMessage.Builder<?> builder) {
			super(builder);
			this.unknownFields = builder.getUnknownFields();
		}

		private CalResponse(boolean noInit) {
			this.unknownFields = com.google.protobuf.UnknownFieldSet
					.getDefaultInstance();
		}

		private static final CalResponse defaultInstance;

		public static CalResponse getDefaultInstance() {
			return defaultInstance;
		}

		public CalResponse getDefaultInstanceForType() {
			return defaultInstance;
		}

		private final com.google.protobuf.UnknownFieldSet unknownFields;

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
			return this.unknownFields;
		}

		private CalResponse(com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			initFields();
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
					.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						done = true;
						break;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							done = true;
						}
						break;
					}
					case 8: {
						bitField0_ |= 0x00000001;
						result_ = input.readInt32();
						break;
					}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
						e.getMessage()).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
			return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalResponse_descriptor;
		}

		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
			return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
							com.zxf.rpc.proto.CalculatorMsg.CalResponse.class,
							com.zxf.rpc.proto.CalculatorMsg.CalResponse.Builder.class);
		}

		public static com.google.protobuf.Parser<CalResponse> PARSER = new com.google.protobuf.AbstractParser<CalResponse>() {
			public CalResponse parsePartialFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws com.google.protobuf.InvalidProtocolBufferException {
				return new CalResponse(input, extensionRegistry);
			}
		};

		@java.lang.Override
		public com.google.protobuf.Parser<CalResponse> getParserForType() {
			return PARSER;
		}

		private int bitField0_;
		// required int32 result = 1;
		public static final int RESULT_FIELD_NUMBER = 1;
		private int result_;

		/**
		 * <code>required int32 result = 1;</code>
		 */
		public boolean hasResult() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		/**
		 * <code>required int32 result = 1;</code>
		 */
		public int getResult() {
			return result_;
		}

		private void initFields() {
			result_ = 0;
		}

		private byte memoizedIsInitialized = -1;

		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			if (!hasResult()) {
				memoizedIsInitialized = 0;
				return false;
			}
			memoizedIsInitialized = 1;
			return true;
		}

		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeInt32(1, result_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream.computeInt32Size(
						1, result_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof com.zxf.rpc.proto.CalculatorMsg.CalResponse)) {
				return super.equals(obj);
			}
			com.zxf.rpc.proto.CalculatorMsg.CalResponse other = (com.zxf.rpc.proto.CalculatorMsg.CalResponse) obj;

			boolean result = true;
			result = result && (hasResult() == other.hasResult());
			if (hasResult()) {
				result = result && (getResult() == other.getResult());
			}
			result = result
					&& getUnknownFields().equals(other.getUnknownFields());
			return result;
		}

		private int memoizedHashCode = 0;

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptorForType().hashCode();
			if (hasResult()) {
				hash = (37 * hash) + RESULT_FIELD_NUMBER;
				hash = (53 * hash) + getResult();
			}
			hash = (29 * hash) + getUnknownFields().hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseDelimitedFrom(
				java.io.InputStream input) throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseDelimitedFrom(input, extensionRegistry);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return PARSER.parseFrom(input);
		}

		public static com.zxf.rpc.proto.CalculatorMsg.CalResponse parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return PARSER.parseFrom(input, extensionRegistry);
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(
				com.zxf.rpc.proto.CalculatorMsg.CalResponse prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code CalResponse}
		 */
		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder> implements
				com.zxf.rpc.proto.CalculatorMsg.CalResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
				return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalResponse_descriptor;
			}

			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
				return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalResponse_fieldAccessorTable
						.ensureFieldAccessorsInitialized(
								com.zxf.rpc.proto.CalculatorMsg.CalResponse.class,
								com.zxf.rpc.proto.CalculatorMsg.CalResponse.Builder.class);
			}

			// Construct using
			// com.newegg.ec.rpc.proto.CalculatorMsg.CalResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
					com.google.protobuf.GeneratedMessage.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			public Builder clear() {
				super.clear();
				result_ = 0;
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
				return com.zxf.rpc.proto.CalculatorMsg.internal_static_CalResponse_descriptor;
			}

			public com.zxf.rpc.proto.CalculatorMsg.CalResponse getDefaultInstanceForType() {
				return com.zxf.rpc.proto.CalculatorMsg.CalResponse
						.getDefaultInstance();
			}

			public com.zxf.rpc.proto.CalculatorMsg.CalResponse build() {
				com.zxf.rpc.proto.CalculatorMsg.CalResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			public com.zxf.rpc.proto.CalculatorMsg.CalResponse buildPartial() {
				com.zxf.rpc.proto.CalculatorMsg.CalResponse result = new com.zxf.rpc.proto.CalculatorMsg.CalResponse(
						this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.result_ = result_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof com.zxf.rpc.proto.CalculatorMsg.CalResponse) {
					return mergeFrom((com.zxf.rpc.proto.CalculatorMsg.CalResponse) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(
					com.zxf.rpc.proto.CalculatorMsg.CalResponse other) {
				if (other == com.zxf.rpc.proto.CalculatorMsg.CalResponse
						.getDefaultInstance())
					return this;
				if (other.hasResult()) {
					setResult(other.getResult());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			public final boolean isInitialized() {
				if (!hasResult()) {

					return false;
				}
				return true;
			}

			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.zxf.rpc.proto.CalculatorMsg.CalResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input,
							extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (com.zxf.rpc.proto.CalculatorMsg.CalResponse) e
							.getUnfinishedMessage();
					throw e;
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			// required int32 result = 1;
			private int result_;

			/**
			 * <code>required int32 result = 1;</code>
			 */
			public boolean hasResult() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			/**
			 * <code>required int32 result = 1;</code>
			 */
			public int getResult() {
				return result_;
			}

			/**
			 * <code>required int32 result = 1;</code>
			 */
			public Builder setResult(int value) {
				bitField0_ |= 0x00000001;
				result_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>required int32 result = 1;</code>
			 */
			public Builder clearResult() {
				bitField0_ = (bitField0_ & ~0x00000001);
				result_ = 0;
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:CalResponse)
		}

		static {
			defaultInstance = new CalResponse(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:CalResponse)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_CalRequest_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CalRequest_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_CalResponse_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_CalResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = { "\n\023CalculatorMsg.proto\"<\n\nCalRequest\022\022\n\nm"
				+ "ethodName\030\001 \002(\t\022\014\n\004num1\030\002 \002(\005\022\014\n\004num2\030\003 "
				+ "\002(\005\"\035\n\013CalResponse\022\016\n\006result\030\001 \002(\005B.\n\027co"
				+ "m.newegg.ec.rpc.protoB\rCalculatorMsg\210\001\001\240"
				+ "\001\001" };
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
			public com.google.protobuf.ExtensionRegistry assignDescriptors(
					com.google.protobuf.Descriptors.FileDescriptor root) {
				descriptor = root;
				internal_static_CalRequest_descriptor = getDescriptor()
						.getMessageTypes().get(0);
				internal_static_CalRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_CalRequest_descriptor,
						new java.lang.String[] { "MethodName", "Num1", "Num2", });
				internal_static_CalResponse_descriptor = getDescriptor()
						.getMessageTypes().get(1);
				internal_static_CalResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
						internal_static_CalResponse_descriptor,
						new java.lang.String[] { "Result", });
				return null;
			}
		};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(
						descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {},
						assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}